name: Merge Dependabot PRs
on:
  schedule:
    - cron: '0 9 * * 1'  # Run this workflow every Monday at 9:00
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.DEPENDABOT_MERGER_PAT }}" | gh auth login --with-token

      - name: Set Git user identity
        run: |
          git config user.email "dependabot-merger-bot@branch.io"
          git config user.name "Dependabot Merger Bot"

      - name: Get current date and time
        id: datetime
        run: echo "::set-output name=date::$(date +'%m-%d-%Y-%H-%M')"

      - name: Create new branch based on date and time
        id: create_new_branch
        run: |
          NEW_BRANCH="dependabot-test-${{ steps.datetime.outputs.date }}"
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH

      - name: Get list of PRs from dependabot
        id: pr_list
        run: |
          PR_LIST=$(gh pr list --json number,headRefName --jq '.[] | "\(.number) \(.headRefName)"' | grep dependabot)
          if [ -z "$PR_LIST" ]; then
            echo "No PRs from dependabot found."
            exit 0
          fi
          echo "::set-output name=numbers::$PR_LIST"
          PR_COUNT=$(echo "$PR_LIST" | wc -l)
          echo "$PR_COUNT PR's to be merged: $PR_LIST"

      - name: Merge PRs into new branch
        id: merge_prs
        run: |
          NEW_BRANCH="dependabot-test-${{ steps.datetime.outputs.date }}"
          git checkout $NEW_BRANCH
          IFS=$'\n' read -r -a array <<< "${{ steps.pr_list.outputs.numbers }}"
          for item in "${array[@]}"; do
            IFS=' ' read -r PR_NUMBER BRANCH_NAME <<< "$item"
            echo "Merging PR #$PR_NUMBER from branch $BRANCH_NAME into $NEW_BRANCH..."
            git fetch origin $BRANCH_NAME
            git merge --no-commit --allow-unrelated-histories --strategy-option=theirs origin/$BRANCH_NAME
            echo "Pushing changes to $NEW_BRANCH..."
            git commit -m "Merged PR #$PR_NUMBER into $NEW_BRANCH"
            git push origin $NEW_BRANCH
          done

      - name: Merge process status
        run: |
          echo "Merging process completed successfully!"
          echo "New branch name: dependabot-test-${{ steps.datetime.outputs.date }}"

      - name: Post to a Slack channel
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C03RTLRKJQP'
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New iOS Dependabot Testing Branch",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Testing Branch: *<https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/tree/dependabot-test-${{ steps.datetime.outputs.date }}|dependabot-test-${{ steps.datetime.outputs.date }}>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_SDK_BOT_TOKEN }}
