name: Tag & Release

# Manually triggered
# $ gh workflow run -f version=1.40.0 release.yml
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to use for this release.
        required: true

# Builds two frameworks in parallel, then commits checksums, releases
# with the frameworks and checksums attached to the release.
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build xcframework
        working-directory: carthage-files
        run: |
          xcodebuild -scheme Branch-xcframework
          cd build
          zip -rqy Branch.zip Branch.xcframework/
          echo '#checksum for Branch.zip on Github' > checksum
          shasum Branch.zip >> checksum
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: framework
          path: |
            carthage-files/build/Branch.zip
            carthage-files/build/checksum

  build-static:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build static xcframework
        working-directory: carthage-files
        run: |
          xcodebuild -scheme Branch-static-xcframework
          cd build
          zip -rqy Branch_static.zip Branch.xcframework/
          echo '#checksum for Branch-static.zip on Github' > checksum_static
          shasum Branch_static.zip >> checksum_static
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: static-framework
          path: |
            carthage-files/build/Branch_static.zip
            carthage-files/build/checksum_static

  release:
    runs-on: macos-latest
    needs: [build, build-static]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      # The CocoaPods dependencies are only used by the
      # Branch-TestBed.xcworkspace (for unit tests).
      # Bring in the Ruby deps from the cache for quick availability of
      # pod command. Not using cached Pods folder.
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            vendor
            Branch-TestBed/Pods
          key: ${{ runner.os }}-${{ hashFiles('Gemfile.lock','Branch-TestBed/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install Ruby dependencies
        run: |
          bundle config set --local path vendor
          bundle check || bundle install
      - name: Download build artifacts
        uses: actions/download-artifact@v2
      - name: Relocate checksum artifacts
        run: |
          cp framework/checksum carthage-files
          cp static-framework/checksum_static carthage-files
      # The sha output from this step is the commit to be tagged.
      - name: Commit checksums
        id: commit-checksums
        run: |
          git config user.name "Branch SDK Team"
          git config user.email branch-sdks@branch.io
          git commit carthage-files/checksum carthage-files/checksum_static -m'Updated checksums'
          echo "::set-output name=sha::$(git rev-parse HEAD)"
      # TODO: Version bump along the way, probably here.
      - name: Push changes
        run: |
          git push
      - name: Publish to CocoaPods
        run: |
          # TODO: Authenticate
          # bundle exec pod trunk push Branch.podspec
          echo "TODO: This 👆"
      # 3. Create GitHub release. Also creates a tag.
      - name: Create GitHub Release
        uses: actions/github-script@v4
        with:
          script: |
            const createRelease = require('./.github/custom-scripts/create-release');
            const tagName = '${{ github.event.inputs.tag }}';
            const sha = '${{ steps.commit-checksums.outputs.sha }}';
            await createRelease({
              core,
              context,
              github,
              sha,
              version: tagName,
            });
      - name: Upload Release Assets
        uses: actions/github-script@v4
        with:
          script: |
            const uploadAsset = require('./.github/custom-scripts/upload-asset');
            const tagName = '${{ github.event.inputs.tag }}';

            const { data } = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tagName,
            });

            console.log(`Got release ${JSON.stringify(data)}`);

            const uploadUrl = data.upload_url;
            console.log(`Using upload URL for release assets: ${uploadUrl}.`);

            await uploadAsset({
              github,
              assetName: 'Branch.zip',
              path: 'framework/Branch.zip',
              contentType: 'application/zip',
              uploadUrl,
            });
            await uploadAsset({
              github,
              assetName: 'Branch_static.zip',
              path: 'static-framework/Branch.zip',
              contentType: 'application/zip',
              uploadUrl,
            });
            await uploadAsset({
              github,
              assetName: 'checksum.txt',
              path: 'framework/checksum',
              contentType: 'text/plain',
              uploadUrl,
            });
            await uploadAsset({
              github,
              assetName: 'checksum_static.txt',
              path: 'static-framework/checksum_static',
              contentType: 'text/plain',
              uploadUrl,
            });
      - name: Report Release
        run: |
          echo "Created release ${{ github.event.inputs.tag }}:"
          echo " https://github.com/${{ env.GITHUB_REPOSITORY }}/release/${{ github.event.inputs.tag }}"
      # 4. Trigger import workflow in ios-spm repo.
      - name: Export to ios-spm repository
        uses: actions/github-script@v4
        with:
          script: |
            console.log('TODO: This 👆');
