name: Update Changelog on Readme.com

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print release information
      run: |
        echo "Name: ${{ github.event.release.name }}"
        echo "Description: ${{ github.event.release.body }}"
    
    - name: Format release notes
      id: format
      run: |
        release_name="${{ github.event.release.name }}"
        release_body="${{ github.event.release.body }}"
        formatted_date=$(date +"%Y-%B-%d")
        formatted_notes="## v$release_name\n\n**($formatted_date)**\n\n$release_body"
        
        echo -e "$formatted_notes"
        echo "formatted_notes=$formatted_notes" >> $GITHUB_OUTPUT
    
    - name: Update ReadMe Documentation
      uses: readmeio/rdme@v8
      with:
        key: ${{ secrets.README_API_KEY }}
        version: "main"
        doc: "ios-version-history"
        prepend: ${{ steps.format.outputs.formatted_notes }}