name: Update Changelog on Readme.com

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get release notes
      id: get_release_notes
      run: echo "::set-output name=release_notes::$(jq -r .release.body $GITHUB_EVENT_PATH)"

    - name: Print release notes
      run: echo "Release notes; ${{ steps.get_release_notes.outputs.release_notes }}"